#Active profile:
spring.profiles.active=dev
#spring.profiles.active=test-failure

# Application
    spring.application.name=Varthak-Assessment
    customer.api.token=${CUSTOMER_API_TOKEN}

    # =========================
    # Your Database
    # =========================
    spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
    spring.datasource.username=varthak_app
    spring.datasource.password=app123
    spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

    # Flyway Configuration
    spring.flyway.enabled=true
    spring.flyway.locations=classpath:db/migration
    spring.flyway.schemas=VARTHAK_APP

    # JPA / Hibernate
    # =========================
    spring.jpa.hibernate.ddl-auto=validate
    spring.jpa.show-sql=true
    spring.jpa.properties.hibernate.format_sql=true
    spring.jpa.database-platform=org.hibernate.dialect.OracleDialect








